services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: repair_crm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - repair-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d repair_crm" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    stop_grace_period: 10s
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    networks:
      - repair-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
    stop_grace_period: 5s
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8030:8000"
    volumes:
      - ./backend:/app
      - media_volume:/app/media
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/repair_crm
      - REDIS_URL=redis://redis:6379/0
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend,0.0.0.0,frontend
        # суперпользователь
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=admin123
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - repair-network
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/health", "||", "exit", "1" ]
#      interval: 30s
#      timeout: 10s
#      retries: 3
#      start_period: 40s
    stop_grace_period: 10s
    restart: unless-stopped
    command: >
        sh -c "
          echo 'Waiting for database...' &&
          sleep 5 &&
          python manage.py makemigrations &&
          python manage.py migrate &&
          echo 'Ensuring superuser...' &&
          python manage.py shell -c 'from init_superuser import run; run()' &&
          echo 'Starting Django server...' &&
          python manage.py runserver 0.0.0.0:8000
        "

  frontend:
    build:
      context: ./frontend/crm-app
      dockerfile: ../../docker/Dockerfile.frontend-dev
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/crm-app:/app
      - /app/node_modules
      - /app/.angular
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NG_CLI_ANALYTICS=false
      - NODE_ENV=development
    networks:
      - repair-network
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
  media_volume:

networks:
  repair-network:
    driver: bridge
